name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload production artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: dist/

      - name: Upload staging artifacts
        if: github.ref == 'refs/heads/staging'
        uses: actions/upload-artifact@v2
        with:
          name: staging-build
          path: dist/

      - name: Deploy to Vercel (Staging)
        if: github.ref == 'refs/heads/staging'
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/master'
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
